[oadp-1.2] upgrade x/net to 0.17.0
openshift/restic pull request #26
Opened 2023-10-17 22:59 UTC by sseago

2023-10-17 23:30 UTC, weshayutin approved these changes

2023-10-17 23:59 UTC, shubham-pampattiwar approved these changes

2023-10-18 00:39 UTC, kaovilai requested changes
go.mod contains go1.18 line 73

2023-10-18 12:15 UTC, mpryc commented
Note CI config to enable unit-test: https://github.com/openshift/release/pull/44529

2023-10-18 13:16 UTC, weshayutin approved these changes

2023-10-18 13:16 UTC, merged