[konveyor-0.15.0] upgrade x/net to 0.17.0
openshift/restic pull request #27
Opened 2023-10-17 23:00 UTC by sseago

2023-10-17 23:30 UTC, weshayutin approved these changes

2023-10-17 23:59 UTC, shubham-pampattiwar approved these changes

2023-10-18 00:41 UTC, kaovilai requested changes
go.mod contains go1.18 line 73

2023-10-18 15:34 UTC, kaovilai approved these changes

2023-10-18 15:50 UTC, merged