[konveyor-0.14.0] upgrade x/net to 0.17.0`
openshift/restic pull request #29
Opened 2023-10-17 23:08 UTC by sseago

2023-10-17 23:30 UTC, weshayutin approved these changes

2023-10-17 23:58 UTC, shubham-pampattiwar approved these changes

2023-10-18 00:42 UTC, kaovilai requested changes
go.mod contains go1.15 line 49

2023-10-18 15:31 UTC, kaovilai approved these changes

2023-10-18 15:31 UTC, kaovilai commented
/lgtm

2023-10-18 15:54 UTC, merged